apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/postgresq
