kind: Service
apiVersion: v1
metadata:
  name: quarkus-postgres-k8s
  labels:
    name: quarkus-postgres-k8s
spec:
  ports:
  - nodePort: 30165
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: quarkus-postgres-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-postgres-k8s
spec:
  selector:
    matchLabels:
      app: quarkus-postgres-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus-postgres-k8s
    spec:
      containers:
      - name: quarkus-postgres-k8s
        image: antiman0101/football-players:2.4 # Docker Hub/Registry
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres_password
